apiVersion: v1
kind: Namespace
metadata:
  name: awesome
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: front-rollout
  namespace: awesome
  labels:
    app: front
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: 1234567.dkr.ecr.ap-northeast-2.amazonaws.com/awesome-front:44
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
        resources:
          requests:
            cpu: 200m
  strategy:
    blueGreen: 
      #activeService는 이전의 배포된 Blue 서비스
      activeService: frontsvc-blue
      #previewService는 새롭게 배포될 Green 서비스
      previewService: frontsvc-green
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: frontsvc-blue
  namespace: awesome
  labels:
    app: front
spec:
  selector:
    app: front
  type: NodePort
  ports:
  - nodePort: 30011
    port: 10000
    targetPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: frontsvc-green
  namespace: awesome
  labels:
    app: front
spec:
  selector:
    app: front
  type: NodePort
  ports:
  - nodePort: 30111             
    port: 10000
    targetPort: 10000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-hpa
  namespace: awesome
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: front-rollout
  targetCPUUtilizationPercentage: 50